---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: "molecule-minio-${MOLECULE_DISTRO:-bookworm}"
    image: "${REGISTRY_PROXY_URL}jdubz/ci-systemd:1.0-${MOLECULE_DISTRO:-bookworm}"
    privileged: true
    pre_build_image: true
    override_command: false
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
